POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpbXBwYTg4IiwiaWQiOiI1YjViMGQyOTNhNGMwOTFlNTg1MTQ1MTkiLCJpYXQiOjE1MzI5NDY3NjZ9.TJYeTsGwLUegF3VerQAMgh2gKWis8TwNbkxNRa3n_-k

{
    "title": "timen bloki with middleware3",
    "author": "time88121",
    "url": "http://yle.fi/bloki",
    "likes": 11122
}